name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./ci.db
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install all dependencies
        run: pip install -r requirements-dev.txt
      - name: tests with pytest
        run: pytest